name: tag_test
on:   
   push:
     branches: [dev, main]
     tags:
        - 'dev-rc*'
   pull_request:
     branches: [dev, main]
   
   #push:
   # tags:
   #   - 'dev-rc*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: getCommitMessage
      run: |
        echo '${{ github.event.head_commit.message }}'
      id: tag_name 
